PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX qa: <http://www.wdaqua.eu/qa#>

ASK
FROM <GRAPHID>
WHERE {
  {
    SELECT (COUNT(?annotationId) AS ?annotations)
    WHERE {
      ?annotationId rdf:type qa:AnnotationOfInstance.
      ?annotationId oa:hasBody ?body.
      ?annotationId oa:hasTarget ?target.
      ?annotationId oa:annotatedAt ?date.
      ?annotationId oa:annotatedBy <urn:qanary:MyQanaryPipeline2>.
    }
  }
  FILTER(?annotations > 1)
}
