PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX qa: <http://www.wdaqua.eu/qa#>

ASK 
FROM <GRAPHID>
WHERE
{
    GRAPH ?graphid {
        ?annotation oa:annotatedBy ?component .
        ?annotation rdf:type qa:AnnotationOfAnswerSPARQL .
    FILTER(?component = <urn:qanary:QB-BirthDataWikidata> || ?component = <urn:qanary:QAnswerQueryBuilderAndQueryCandidateFetcher>)
    }
}